name: stream_isolate
description: An isolate wrapper for stream-powered intercommunication.
version: 0.1.0
homepage: https://github.com/abion47/stream_isolate
repository: https://github.com/abion47/stream_isolate
issue_tracker: https://github.com/abion47/stream_isolate/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
