name: stream_isolate
description: A utility wrapper class for working with isolates using stream-powered intercommunication.
version: 0.2.0
homepage: https://github.com/abion47/stream_isolate
repository: https://github.com/abion47/stream_isolate
issue_tracker: https://github.com/abion47/stream_isolate/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
